### ISSUE TITLE
Parse/read the csv and output to a csv file

### ISSUE THREAD

**Issue by mobgbfm** [mobgbfm/GPA3#2]
- [ ] Read specific column formal education from dataset .csv and import to x.csv

**Comment by rkok3210** [comment]
Michael's code hit an error whci Paul that was a dodgy character. Michael to look at again.

**Comment by sarahmcandrew** [comment]
For next week: 

- [x] Michael to attempt to get rid of the NA columns from csv file

- [ ] Eva to read from the parse csv file and create a loop for read first three letters and add counter

- [ ] Sarah to assist creating loop for read through file and add a counter
